spring:
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: client_group
        topic:
            clientsToRegistration: clientsToRegistration
            clientsRegistered: clientsRegistered
    application:
        name: kafka-example
    datasource:
        url: jdbc:postgresql://localhost:5433/
        username: postgres
        password: "0000"
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop